### ISSUE TITLE
YesLap API - Login e sign  

### ISSUE THREAD

**Issue by MatheusDomingosDev** [YesLap/Back-End#1]
@ThallyssonKlein de acordo com a doc de API, desenvolver os end-points referente ao cadastro e ao login. 

https://docs.google.com/document/d/1vKEIoUHh3tA4QEO-hwb4mSTUJ_lXu93NVdA6fLfM14E/edit?usp=sharing

**Comment by ThallyssonKlein** [comment]
@MatheusDomingosDev tudo pronto.
